name = "Life"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["life"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Life"

[[lean_exe]]
name = "life"
root = "Life.Basic"
